export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';

export const GET_SHOPPING_HISTORY_REQUEST = 'GET_SHOPPING_HISTORY_REQUEST';
export const GET_SHOPPING_HISTORY_SUCCESS = 'GET_SHOPPING_HISTORY_SUCCESS';
export const GET_SHOPPING_HISTORY_FAIL = 'GET_SHOPPING_HISTORY_FAIL';

export const CREATE_SHOPPING_HISTORY_REQUEST =
  'CREATE_SHOPPING_HISTORY_REQUEST';
export const CREATE_SHOPPING_HISTORY_SUCCESS =
  'CREATE_SHOPPING_HISTORY_SUCCESS';
export const CREATE_SHOPPING_HISTORY_FAIL = 'CREATE_SHOPPING_HISTORY_FAIL';

export const UPDATE_SHOPPING_STATUS_REQUEST = 'UPDATE_SHOPPING_STATUS_REQUEST';
export const UPDATE_SHOPPING_STATUS_SUCCESS = 'UPDATE_SHOPPING_STATUS_SUCCESS';
export const UPDATE_SHOPPING_STATUS_FAIL = 'UPDATE_SHOPPING_STATUS_FAIL';
